# Use DecapBridge auth (required)
backend:
  name: git-gateway
  repo: martusheff/nativityofthemotherofgod
  branch: main
  identity_url: https://auth.decapbridge.com/sites/71fd480a-4bbf-4d86-aea5-45d2b70a1764
  gateway_url: https://gateway.decapbridge.com
  local_backend: true

  # Quickly see who did what (optional)
  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

# Better Decap + Bridge logo (optional)
logo_url: https://decapbridge.com/decapcms-with-bridge.svg

# Add site links in DecapCMS (optional)
site_url: https://nativityofthemotherofgod.com

collections:
  - name: pages
    label: Pages
    files:
      - file: "content/pages/home.md"
        label: "Home"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Sub Title", name: "subTitle", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Hero Image", name: "heroImage", widget: "image" }
          - { label: "Hero Image Description", name: "heroImageDescription", widget: "string" }
          - { label: "Hero Primary CTA Button Label", name: "heroPrimaryCTALabel", widget: "string" }
          - { label: "Hero Primary CTA Button URL", name: "heroPrimaryCTAURL", widget: "string" }
          - { label: "Hero Secondary CTA Button Label", name: "heroSecondaryCTALabel", widget: "string" }
          - { label: "Hero Secondary CTA Button URL", name: "heroSecondaryCTAURL", widget: "string" }

      - file: "content/pages/donate.md"
        label: "Donate"
        name: "donate"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
  
  - name: "articles"
    label: "Articles"
    label_singular: "Article"
    folder: "/content/articles"
    create: true
    slug: "{{slug}}"
    summary: "{{date | date('MM/DD/YYYY')}} | {{title | upper}}"

    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string"}
      - { label: "Author", name: "author", widget: "string", default: "Fr Nikita" }
      - { label: "Date", name: "date", widget: "datetime", default: "{{now}}" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: 'Content', name: 'body', widget: 'markdown' }
      - { label: "Signature", name: "signature", widget: "string"}

  - name: "events"
    label: "Schedule"
    label_singular: "Event"
    folder: "/content/events"
    create: true
    slug: "{{date | date('YYYY-MM-DDTHH-mm-ss')}}"
    extension: "json"
    summary: "{{date | date('MM/DD/YYYY')}} | {{title | upper}}"
    format: "json"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ssZ", default: "{{now}}" }
  
  - name: "timeline"
    label: "Timeline"
    folder: "/content/timeline"
    create: true
    slug: "{{date | date('YYYY-MM-DDTHH-mm-ss')}}"
    extension: "json"
    summary: "{{date | date('MM/DD/YYYY')}} | {{title | upper}}"
    format: "json"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ssZ", default: "{{now}}" }



  - name: "config"
    label: "Config"
    files:
      - file: "content/config/meta.json"
        label: "Meta"
        name: "meta"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
      - file: "content/config/weekly-services.json"
        label: "Weekly Services"
        name: "weekly-services"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }